### PR TITLE
Updated jetty-client

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated jetty-reactive-httpclient to avoid vulnerability problem with jetty-io

### CODE REVIEW

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.3.6`

**Comment by olenagerasimova** [comment]
@g4s8 please, could you help with release here?

**Comment by g4s8** [comment]
> @g4s8 please, could you help with release here?

@olenagerasimova sure, [0.3.6](https://github.com/artipie/http-client/releases/tag/0.3.6) is ready

**Pull request merged**
