### PR TITLE
deps: bump `ppom` from `0.4` to `v1.1.3`

### PR DESCRIPTION
**Pull request by baudoliver7**
Close: #78

### CODE REVIEW

**Comment by baudoliver7** [comment]
@olenagerasimova good now to be reviewed

**Review by olenagerasimova — CHANGES_REQUESTED** [review]
@baudoliver7 please, check junut dependencies: we have them in ppom, only `junit-jupiter-params` should be present here. Also, the latest version of ppom is `v1.1.3`.

**Comment by baudoliver7** [comment]
> @baudoliver7 please, check junut dependencies: we have them in ppom, only `junit-jupiter-params` should be present here. Also, the latest version of ppom is `v1.1.3`.

@olenagerasimova ok for junit dependencies. For `ppom`, `1.1.3` is not deployed in Maven repositories (you can look at maven version tag in README).

**Comment by olenagerasimova** [comment]
@baudoliver7 

> For ppom, 1.1.3 is not deployed in Maven repositories (you can look at maven version tag in README).

it's with `v`, defiantly is deployed in maven and [used](https://github.com/artipie/maven-adapter/blob/3befc365a9370eaca62765c4bace79c2188931e2/pom.xml#L30) in maven-adapter.

**Comment by baudoliver7** [comment]
@olenagerasimova It seems ok now.

**Review by olenagerasimova — APPROVED** [review]
@baudoliver7 thanks, merging

**Pull request merged**
